name: Test
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allows running this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    # где заускаем
    runs-on: ubuntu-latest
    # что делаем
    steps:
      # выкачиваем репозиторий
      - uses: actions/checkout@v4
      # настраиваем java
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      # запускаем тесты
      - run: gradle clean positive
      # скачиваем историю тестов
      - uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages
      # генерируем отчет
      - uses: simple-elf/allure-report-action@master
        if: always()
        with:
          gh_pages: gh-pages
          allure_results: build/allure-results
          allure_report: allure-report
          allure_history: allure-history
      # публикуем отчет
      - uses: peaceiris/actions-gh-pages@v2
        if: always()
        env:
          PERSONAL_TOKEN: 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
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history